// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/list-products.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^4.4.3";
import { PRODUCTS } from "npm:@/data/products";
var list_products_default = defineTool({
  name: "list_products",
  title: "Listar produtos",
  description: "Lista os produtos do cat\xE1logo da Pientro Casa. Pode filtrar por categoria (caixa, vaso, quadro, objeto) e por cole\xE7\xE3o.",
  inputSchema: {
    category: z.enum(["caixa", "vaso", "quadro", "objeto"]).optional().describe("Filtra por categoria do produto."),
    collection: z.string().optional().describe("Slug da cole\xE7\xE3o, por exemplo 'sol-da-manha'.")
  },
  annotations: {
    readOnlyHint: true,
    idempotentHint: true,
    openWorldHint: false
  },
  handler: ({ category, collection }) => {
    const items = PRODUCTS.filter(
      (p) => (!category || p.category === category) && (!collection || p.collection === collection)
    ).map((p) => ({
      slug: p.slug,
      name: p.name,
      category: p.category,
      collection: p.collection,
      price: p.price,
      compareAt: p.compareAt ?? null,
      tagline: p.tagline
    }));
    return {
      content: [
        {
          type: "text",
          text: `${items.length} produto(s) encontrado(s).`
        }
      ],
      structuredContent: { products: items }
    };
  }
});

// src/lib/mcp/tools/get-product.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^4.4.3";
import { getProductBySlug } from "npm:@/data/products";
var get_product_default = defineTool2({
  name: "get_product",
  title: "Detalhes do produto",
  description: "Retorna os detalhes completos de um produto da Pientro Casa a partir do seu slug (ex.: 'vaso-alto-sol-da-manha').",
  inputSchema: {
    slug: z2.string().min(1).describe("Slug do produto.")
  },
  annotations: {
    readOnlyHint: true,
    idempotentHint: true,
    openWorldHint: false
  },
  handler: ({ slug }) => {
    const p = getProductBySlug(slug);
    if (!p) {
      return {
        content: [{ type: "text", text: `Produto n\xE3o encontrado: ${slug}` }],
        isError: true
      };
    }
    return {
      content: [
        {
          type: "text",
          text: `${p.name} \u2014 ${p.tagline}. Pre\xE7o: R$ ${p.price.toFixed(2)}.`
        }
      ],
      structuredContent: {
        product: {
          slug: p.slug,
          name: p.name,
          shortName: p.shortName,
          category: p.category,
          collection: p.collection,
          price: p.price,
          compareAt: p.compareAt ?? null,
          tagline: p.tagline,
          description: p.description,
          highlights: p.highlights,
          variants: p.variants ?? []
        }
      }
    };
  }
});

// src/lib/mcp/tools/list-collection.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^4.4.3";
import { getProductsByCollection } from "npm:@/data/products";
var list_collection_default = defineTool3({
  name: "list_collection",
  title: "Listar cole\xE7\xE3o",
  description: "Lista todos os produtos de uma cole\xE7\xE3o da Pientro Casa (ex.: 'sol-da-manha').",
  inputSchema: {
    collection: z3.string().min(1).describe("Slug da cole\xE7\xE3o.")
  },
  annotations: {
    readOnlyHint: true,
    idempotentHint: true,
    openWorldHint: false
  },
  handler: ({ collection }) => {
    const items = getProductsByCollection(collection).map((p) => ({
      slug: p.slug,
      name: p.name,
      category: p.category,
      price: p.price,
      tagline: p.tagline
    }));
    return {
      content: [
        {
          type: "text",
          text: `${items.length} pe\xE7a(s) na cole\xE7\xE3o "${collection}".`
        }
      ],
      structuredContent: { collection, products: items }
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "pientro-casa-mcp",
  title: "Pientro Casa MCP",
  version: "0.1.0",
  instructions: "Ferramentas para explorar o cat\xE1logo da Pientro Casa \u2014 curadoria de decora\xE7\xE3o com olhar de arquiteta. Use `list_products` para navegar o cat\xE1logo (filtrando por categoria ou cole\xE7\xE3o), `list_collection` para pe\xE7as de uma cole\xE7\xE3o espec\xEDfica e `get_product` para detalhes completos de um produto pelo slug.",
  tools: [list_products_default, get_product_default, list_collection_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
