// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/list-products.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^4.4.3";

// src/lib/mcp/data.ts
var MCP_PRODUCTS = [
  {
    slug: "caixa-decorativa-media",
    name: "Caixa Decorativa M\xE9dia \u2014 Terracota & Dourado",
    shortName: "Caixa M\xE9dia",
    category: "caixa",
    collection: "sol-da-manha",
    price: 159.2,
    compareAt: 199,
    tagline: "Composi\xE7\xE3o em camadas, com peso visual leve",
    description: "Mais do que organizar, pe\xE7as pensadas para compor ambientes com eleg\xE2ncia e inten\xE7\xE3o.",
    highlights: [
      "Tampa de madeira maci\xE7a",
      "Acabamento em terracota fosco",
      "Detalhe em folha dourada"
    ]
  },
  {
    slug: "caixa-decorativa-grande",
    name: "Caixa Decorativa Grande \u2014 Terracota & Dourado",
    shortName: "Caixa Grande",
    category: "caixa",
    collection: "sol-da-manha",
    price: 199.2,
    compareAt: 249,
    tagline: "Pe\xE7a \xE2ncora para console, mesa lateral ou nicho",
    description: "Mais do que organizar, pe\xE7as pensadas para compor ambientes com eleg\xE2ncia e inten\xE7\xE3o.",
    highlights: [
      "Tampa de madeira maci\xE7a",
      "Acabamento em terracota fosco",
      "Detalhe em folha dourada"
    ]
  },
  {
    slug: "vaso-medio-sol-da-manha",
    name: "Vaso M\xE9dio em Vidro \u2014 Fio Dourado",
    shortName: "Vaso M\xE9dio",
    category: "vaso",
    collection: "sol-da-manha",
    price: 179,
    compareAt: 219,
    tagline: "Silhueta oval em vidro cristal com borda em fio dourado",
    description: "Vaso em vidro soprado transparente (21 \xD7 17 \xD7 17 cm) com borda finalizada em fio dourado aplicado \xE0 m\xE3o. Pe\xE7a artesanal \u2014 pequenas varia\xE7\xF5es fazem parte do charme.",
    highlights: [
      "Vidro soprado transparente \u2014 pe\xE7a \xFAnica",
      "Borda em fio dourado aplicado \xE0 m\xE3o",
      "21 \xD7 17 \xD7 17 cm (A \xD7 L \xD7 \xD8)",
      "Ideal para galhos secos, pampas e flores de haste longa"
    ]
  },
  {
    slug: "vaso-baixo-sol-da-manha",
    name: "Vaso Baixo em Vidro \u2014 Fio Dourado",
    shortName: "Vaso Baixo",
    category: "vaso",
    collection: "sol-da-manha",
    price: 149,
    compareAt: 189,
    tagline: "Volume arredondado em vidro cristal com borda em fio dourado",
    description: "Vaso baixo em vidro soprado transparente (13 \xD7 16,5 \xD7 16,5 cm), com corpo arredondado e borda em fio dourado feito \xE0 m\xE3o. Comp\xF5e dupla com o vaso m\xE9dio.",
    highlights: [
      "Vidro soprado transparente \u2014 pe\xE7a \xFAnica",
      "Borda em fio dourado aplicado \xE0 m\xE3o",
      "13 \xD7 16,5 \xD7 16,5 cm (A \xD7 L \xD7 \xD8)",
      "Perfeito para arranjos baixos ou como objeto solo"
    ]
  },
  {
    slug: "quadro-sol-da-manha",
    name: "Quadro Sol da Manh\xE3",
    shortName: "Quadro",
    category: "quadro",
    collection: "sol-da-manha",
    price: 229,
    compareAt: 289,
    tagline: "Arte abstrata em terracota e dourado",
    description: "Impress\xE3o fine art em papel algod\xE3o 310g, com moldura em carvalho natural e passepartout cru.",
    highlights: [
      "Impress\xE3o fine art 310g/m\xB2",
      "Moldura em carvalho natural",
      "Edi\xE7\xE3o limitada e numerada"
    ]
  },
  {
    slug: "lupa-polirresina-sol-da-manha",
    name: "Lupa Decorativa em Polirresina Dourada",
    shortName: "Lupa Decorativa",
    category: "objeto",
    collection: "sol-da-manha",
    price: 139,
    compareAt: 179,
    tagline: "Adorno de mesa com aro dourado e base em polirresina",
    description: "Lupa decorativa (16,5 \xD7 7,5 \xD7 1,5 cm) com aro em polirresina dourada e cabo em polirresina. Pe\xE7a de mesa que remete a bibliotecas e ateliers.",
    highlights: [
      "Aro em polirresina com acabamento dourado",
      "Cabo em polirresina",
      "16,5 \xD7 7,5 \xD7 1,5 cm (A \xD7 L \xD7 P)",
      "Ideal para consoles, escrivaninhas e estantes"
    ]
  }
];
var getMcpProductBySlug = (slug) => MCP_PRODUCTS.find((p) => p.slug === slug);
var getMcpProductsByCollection = (collection) => MCP_PRODUCTS.filter((p) => p.collection === collection);

// src/lib/mcp/tools/list-products.ts
var list_products_default = defineTool({
  name: "list_products",
  title: "Listar produtos",
  description: "Lista os produtos do cat\xE1logo da Pientro Casa. Pode filtrar por categoria (caixa, vaso, quadro, objeto) e por cole\xE7\xE3o.",
  inputSchema: {
    category: z.enum(["caixa", "vaso", "quadro", "objeto"]).optional().describe("Filtra por categoria do produto."),
    collection: z.string().optional().describe("Slug da cole\xE7\xE3o, por exemplo 'sol-da-manha'.")
  },
  annotations: {
    readOnlyHint: true,
    idempotentHint: true,
    openWorldHint: false
  },
  handler: ({ category, collection }) => {
    const items = MCP_PRODUCTS.filter(
      (p) => (!category || p.category === category) && (!collection || p.collection === collection)
    ).map((p) => ({
      slug: p.slug,
      name: p.name,
      category: p.category,
      collection: p.collection,
      price: p.price,
      compareAt: p.compareAt ?? null,
      tagline: p.tagline
    }));
    return {
      content: [
        { type: "text", text: `${items.length} produto(s) encontrado(s).` }
      ],
      structuredContent: { products: items }
    };
  }
});

// src/lib/mcp/tools/get-product.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^4.4.3";
var get_product_default = defineTool2({
  name: "get_product",
  title: "Detalhes do produto",
  description: "Retorna os detalhes completos de um produto da Pientro Casa a partir do seu slug (ex.: 'vaso-alto-sol-da-manha').",
  inputSchema: {
    slug: z2.string().min(1).describe("Slug do produto.")
  },
  annotations: {
    readOnlyHint: true,
    idempotentHint: true,
    openWorldHint: false
  },
  handler: ({ slug }) => {
    const p = getMcpProductBySlug(slug);
    if (!p) {
      return {
        content: [{ type: "text", text: `Produto n\xE3o encontrado: ${slug}` }],
        isError: true
      };
    }
    return {
      content: [
        {
          type: "text",
          text: `${p.name} \u2014 ${p.tagline}. Pre\xE7o: R$ ${p.price.toFixed(2)}.`
        }
      ],
      structuredContent: {
        product: {
          slug: p.slug,
          name: p.name,
          shortName: p.shortName,
          category: p.category,
          collection: p.collection,
          price: p.price,
          compareAt: p.compareAt ?? null,
          tagline: p.tagline,
          description: p.description,
          highlights: p.highlights,
          variants: p.variants ?? []
        }
      }
    };
  }
});

// src/lib/mcp/tools/list-collection.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^4.4.3";
var list_collection_default = defineTool3({
  name: "list_collection",
  title: "Listar cole\xE7\xE3o",
  description: "Lista todos os produtos de uma cole\xE7\xE3o da Pientro Casa (ex.: 'sol-da-manha').",
  inputSchema: {
    collection: z3.string().min(1).describe("Slug da cole\xE7\xE3o.")
  },
  annotations: {
    readOnlyHint: true,
    idempotentHint: true,
    openWorldHint: false
  },
  handler: ({ collection }) => {
    const items = getMcpProductsByCollection(collection).map((p) => ({
      slug: p.slug,
      name: p.name,
      category: p.category,
      price: p.price,
      tagline: p.tagline
    }));
    return {
      content: [
        {
          type: "text",
          text: `${items.length} pe\xE7a(s) na cole\xE7\xE3o "${collection}".`
        }
      ],
      structuredContent: { collection, products: items }
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "pientro-casa-mcp",
  title: "Pientro Casa MCP",
  version: "0.1.0",
  instructions: "Ferramentas para explorar o cat\xE1logo da Pientro Casa \u2014 curadoria de decora\xE7\xE3o com olhar de arquiteta. Use `list_products` para navegar o cat\xE1logo (filtrando por categoria ou cole\xE7\xE3o), `list_collection` para pe\xE7as de uma cole\xE7\xE3o espec\xEDfica e `get_product` para detalhes completos de um produto pelo slug.",
  tools: [list_products_default, get_product_default, list_collection_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
